apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-san
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-san
  template:
    metadata:
      labels:
        app: blog-san
    spec:
      containers:
      - name: blog
        image: ghost:2.6-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http:192.168.0.61:30180
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content-san
